# Azure Pipelines for .NET Core app (Web, Function, ....) :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts

jobs:
- job: 'ASPNetCoreWebApp'
  pool:
    vmImage: 'ubuntu-16.04'
    demands: npm
  steps:
  
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.API.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '$(Agent.BuildDirectory)/src/apis/CognitiveOrchestrator.API/nuget.config'

  #- task: DotNetCoreCLI@2
  #  displayName: Restore
  #  inputs:
  #    command: restore
  #    feedsToUse: config
  #    nugetConfigPath: 'src/nuget.config'
  #    projects: '**/*.API.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.API.csproj'
      arguments: '--configuration Release'
      workingDirectory: 'src'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
      workingDirectory: 'src'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: AppDrop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'AppDrop'
      zipAfterPublish: True