# Azure Pipelines for NuGet :)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=vsts

jobs:
- job: 'NuGetCI'
  pool:
    vmImage: 'vs2017-win2016'
    demands: npm

  steps:
  - task: DotNetCoreCLI@2
    displayName: DotNet Restore
    inputs:
      command: restore
      feedsToUse: config
      nugetConfigPath: 'src/nuget.config'
      projects: '**/*.SDK.csproj'

  - task: DotNetCoreCLI@2
    displayName: DotNet Build
    inputs:
      command: build
      projects: '**/*.SDK.csproj'
      arguments: 'Release'
      workingDirectory: 'src'

  - powershell: |
      $Package_CI_Version = "1.0.$(Build.BuildNumber)"
      Write-Host ("##vso[task.setvariable variable=Package_CI_Version;]$Package_CI_Version")
    displayName: 'Update Version'

  - task: DotNetCoreCLI@2
    displayName: 'DotNet Pack'
    inputs:
      command: pack
      packagesToPack: '**/*.SDK.csproj'
      configuration: '$(BuildConfiguration)'
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      nobuild: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'Package_CI_Version'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '$(Build.BuildNumber)'

#  - task: NuGetCommand@2
#    displayName: 'NuGet push'
#    inputs:
#      command: push
#      packagesToPush: '**/Contoso.CognitivePipeline.ClientSDK.*.nupkg;**/Contoso.CognitivePipeline.ClientSDK.*.symbols.nupkg'
#      publishVstsFeed: '$(azureArtifactFeedId)'
#      allowPackageConflicts: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish NuGet Artifact: NuGetCI'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'CustomNuGet'